// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAnswerIndex = "answer_index"

// AnswerIndex mapped from table <answer_index>
type AnswerIndex struct {
	ID           int64     `gorm:"column:id;primaryKey" json:"id"`                                // 主键
	QuestionID   int64     `gorm:"column:question_id;not null" json:"question_id"`                // 问题 id
	UserID       int64     `gorm:"column:user_id;not null" json:"user_id"`                        // 回答者 id
	IPLoc        string    `gorm:"column:ip_loc;not null" json:"ip_loc"`                          // 回答者 IP 归属地
	ApproveCount int32     `gorm:"column:approve_count;not null" json:"approve_count"`            // 赞同数
	LikeCount    int32     `gorm:"column:like_count;not null" json:"like_count"`                  // 喜欢数
	CollectCount int32     `gorm:"column:collect_count;not null" json:"collect_count"`            // 收藏数
	State        int32     `gorm:"column:state;not null" json:"state"`                            // 状态 (0-正常 1-隐藏)
	Attrs        int32     `gorm:"column:attrs" json:"attrs"`                                     // 属性 (待添加)
	CreateTime   time.Time `gorm:"autoCreateTime;column:create_time;not null" json:"create_time"` // 创建时间
	UpdateTime   time.Time `gorm:"autoUpdateTime;column:update_time;not null" json:"update_time"` // 修改时间
}

// TableName AnswerIndex's table name
func (*AnswerIndex) TableName() string {
	return TableNameAnswerIndex
}
