// Code generated by goctl. DO NOT EDIT.
package types

type CrudReq struct {
	Action string `form:"action"`
	Data   string `form:"data"`
}

type CrudRes struct {
	Code int32  `json:"code"`
	Msg  string `json:"msg"`
	Ok   bool   `json:"ok"`
}

type GetCommentSubjectReq struct {
	SubjectId int64 `path:"subject_id"`
}

type GetCommentSubjectRes struct {
	Code int32  `json:"code"`
	Msg  string `json:"msg"`
	Ok   bool   `json:"ok"`
	Data string `json:"data"`
}

type GetCommenSubjectIndexReq struct {
	SubjectId int64 `path:"subject_id"`
	IndexId   int64 `path:"index_id"`
}

type GetCommenSubjectIndexRes struct {
	Code int32  `json:"code"`
	Msg  string `json:"msg"`
	Ok   bool   `json:"ok"`
	Data string `json:"data"`
}

type GetCommentIndexReq struct {
	IndexId int64 `path:"index_id"`
}

type GetCommentIndexRes struct {
	Code int32  `json:"code"`
	Msg  string `json:"msg"`
	Ok   bool   `json:"ok"`
	Data string `json:"data"`
}
