// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"main/app/service/user/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/user/register",
				Handler: RegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/user/login",
				Handler: LoginHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/api/user/nickname",
					Handler: ChangeNicknameHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/user/collection",
					Handler: CreateCollectionHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/api/user/collection/:collectionId",
					Handler: DeleteCollectionHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/user/obj/:obj_type",
					Handler: GetObjInfoHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/user/profile/:userId",
					Handler: GetPersonalInfoHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/user/collection",
					Handler: GetCollectionInfoHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/user/notification/:messageType",
					Handler: GetNotificationInfoHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/user/vip/upgrade",
					Handler: VipUpgradeHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/user/vip/reset",
					Handler: VipResetHandler(serverCtx),
				},
			}...,
		),
	)
}
