// Code generated by goctl. DO NOT EDIT!
// Source: info.proto

package info

import (
	"context"

	"main/app/service/comment/rpc/info/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CommentContent                 = pb.CommentContent
	CommentIndex                   = pb.CommentIndex
	CommentSubject                 = pb.CommentSubject
	GetCommentInfoReq              = pb.GetCommentInfoReq
	GetCommentInfoRes              = pb.GetCommentInfoRes
	GetCommentInfoRes_Data         = pb.GetCommentInfoRes_Data
	GetCommentSubjectIdReq         = pb.GetCommentSubjectIdReq
	GetCommentSubjectIdRes         = pb.GetCommentSubjectIdRes
	GetCommentSubjectIdRes_Data    = pb.GetCommentSubjectIdRes_Data
	GetCommentSubjectIndexReq      = pb.GetCommentSubjectIndexReq
	GetCommentSubjectIndexRes      = pb.GetCommentSubjectIndexRes
	GetCommentSubjectIndexRes_Data = pb.GetCommentSubjectIndexRes_Data
	GetCommentSubjectInfoReq       = pb.GetCommentSubjectInfoReq
	GetCommentSubjectInfoRes       = pb.GetCommentSubjectInfoRes
	GetCommentSubjectInfoRes_Data  = pb.GetCommentSubjectInfoRes_Data

	Info interface {
		GetCommentSubjectId(ctx context.Context, in *GetCommentSubjectIdReq, opts ...grpc.CallOption) (*GetCommentSubjectIdRes, error)
		GetCommentSubjectInfo(ctx context.Context, in *GetCommentSubjectInfoReq, opts ...grpc.CallOption) (*GetCommentSubjectInfoRes, error)
		GetCommentInfo(ctx context.Context, in *GetCommentInfoReq, opts ...grpc.CallOption) (*GetCommentInfoRes, error)
		GetCommentSubjectIndex(ctx context.Context, in *GetCommentSubjectIndexReq, opts ...grpc.CallOption) (*GetCommentSubjectIndexRes, error)
	}

	defaultInfo struct {
		cli zrpc.Client
	}
)

func NewInfo(cli zrpc.Client) Info {
	return &defaultInfo{
		cli: cli,
	}
}

func (m *defaultInfo) GetCommentSubjectId(ctx context.Context, in *GetCommentSubjectIdReq, opts ...grpc.CallOption) (*GetCommentSubjectIdRes, error) {
	client := pb.NewInfoClient(m.cli.Conn())
	return client.GetCommentSubjectId(ctx, in, opts...)
}

func (m *defaultInfo) GetCommentSubjectInfo(ctx context.Context, in *GetCommentSubjectInfoReq, opts ...grpc.CallOption) (*GetCommentSubjectInfoRes, error) {
	client := pb.NewInfoClient(m.cli.Conn())
	return client.GetCommentSubjectInfo(ctx, in, opts...)
}

func (m *defaultInfo) GetCommentInfo(ctx context.Context, in *GetCommentInfoReq, opts ...grpc.CallOption) (*GetCommentInfoRes, error) {
	client := pb.NewInfoClient(m.cli.Conn())
	return client.GetCommentInfo(ctx, in, opts...)
}

func (m *defaultInfo) GetCommentSubjectIndex(ctx context.Context, in *GetCommentSubjectIndexReq, opts ...grpc.CallOption) (*GetCommentSubjectIndexRes, error) {
	client := pb.NewInfoClient(m.cli.Conn())
	return client.GetCommentSubjectIndex(ctx, in, opts...)
}
