// Code generated by goctl. DO NOT EDIT!
// Source: info.proto

package info

import (
	"context"

	"main/app/service/comment/rpc/info/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CommentContent                 = pb.CommentContent
	CommentIndex                   = pb.CommentIndex
	CommentSubject                 = pb.CommentSubject
	GetCommentIndexReq             = pb.GetCommentIndexReq
	GetCommentIndexRes             = pb.GetCommentIndexRes
	GetCommentIndexRes_Data        = pb.GetCommentIndexRes_Data
	GetCommentSubjectIndexReq      = pb.GetCommentSubjectIndexReq
	GetCommentSubjectIndexRes      = pb.GetCommentSubjectIndexRes
	GetCommentSubjectIndexRes_Data = pb.GetCommentSubjectIndexRes_Data
	GetCommentSubjectReq           = pb.GetCommentSubjectReq
	GetCommentSubjectRes           = pb.GetCommentSubjectRes
	GetCommentSubjectRes_Data      = pb.GetCommentSubjectRes_Data

	Info interface {
		GetCommentSubject(ctx context.Context, in *GetCommentSubjectReq, opts ...grpc.CallOption) (*GetCommentSubjectRes, error)
		GetCommentIndex(ctx context.Context, in *GetCommentIndexReq, opts ...grpc.CallOption) (*GetCommentIndexRes, error)
		GetCommentSubjectIndex(ctx context.Context, in *GetCommentSubjectIndexReq, opts ...grpc.CallOption) (*GetCommentSubjectIndexRes, error)
	}

	defaultInfo struct {
		cli zrpc.Client
	}
)

func NewInfo(cli zrpc.Client) Info {
	return &defaultInfo{
		cli: cli,
	}
}

func (m *defaultInfo) GetCommentSubject(ctx context.Context, in *GetCommentSubjectReq, opts ...grpc.CallOption) (*GetCommentSubjectRes, error) {
	client := pb.NewInfoClient(m.cli.Conn())
	return client.GetCommentSubject(ctx, in, opts...)
}

func (m *defaultInfo) GetCommentIndex(ctx context.Context, in *GetCommentIndexReq, opts ...grpc.CallOption) (*GetCommentIndexRes, error) {
	client := pb.NewInfoClient(m.cli.Conn())
	return client.GetCommentIndex(ctx, in, opts...)
}

func (m *defaultInfo) GetCommentSubjectIndex(ctx context.Context, in *GetCommentSubjectIndexReq, opts ...grpc.CallOption) (*GetCommentSubjectIndexRes, error) {
	client := pb.NewInfoClient(m.cli.Conn())
	return client.GetCommentSubjectIndex(ctx, in, opts...)
}
