// Code generated by goctl. DO NOT EDIT!
// Source: token_store.proto

package tokenstore

import (
	"context"

	"gohu/app/service/oauth/rpc/token/store/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CheckTokenReq    = pb.CheckTokenReq
	CheckTokenRes    = pb.CheckTokenRes
	GetTokenReq      = pb.GetTokenReq
	GetTokenRes      = pb.GetTokenRes
	GetTokenRes_Data = pb.GetTokenRes_Data
	OAuth2Token      = pb.OAuth2Token
	RemoveTokenReq   = pb.RemoveTokenReq
	RemoveTokenRes   = pb.RemoveTokenRes
	StoreTokenReq    = pb.StoreTokenReq
	StoreTokenRes    = pb.StoreTokenRes

	TokenStore interface {
		StoreToken(ctx context.Context, in *StoreTokenReq, opts ...grpc.CallOption) (*StoreTokenRes, error)
		CheckToken(ctx context.Context, in *CheckTokenReq, opts ...grpc.CallOption) (*CheckTokenRes, error)
		GetToken(ctx context.Context, in *GetTokenReq, opts ...grpc.CallOption) (*GetTokenRes, error)
		RemoveToken(ctx context.Context, in *RemoveTokenReq, opts ...grpc.CallOption) (*RemoveTokenRes, error)
	}

	defaultTokenStore struct {
		cli zrpc.Client
	}
)

func NewTokenStore(cli zrpc.Client) TokenStore {
	return &defaultTokenStore{
		cli: cli,
	}
}

func (m *defaultTokenStore) StoreToken(ctx context.Context, in *StoreTokenReq, opts ...grpc.CallOption) (*StoreTokenRes, error) {
	client := pb.NewTokenStoreClient(m.cli.Conn())
	return client.StoreToken(ctx, in, opts...)
}

func (m *defaultTokenStore) CheckToken(ctx context.Context, in *CheckTokenReq, opts ...grpc.CallOption) (*CheckTokenRes, error) {
	client := pb.NewTokenStoreClient(m.cli.Conn())
	return client.CheckToken(ctx, in, opts...)
}

func (m *defaultTokenStore) GetToken(ctx context.Context, in *GetTokenReq, opts ...grpc.CallOption) (*GetTokenRes, error) {
	client := pb.NewTokenStoreClient(m.cli.Conn())
	return client.GetToken(ctx, in, opts...)
}

func (m *defaultTokenStore) RemoveToken(ctx context.Context, in *RemoveTokenReq, opts ...grpc.CallOption) (*RemoveTokenRes, error) {
	client := pb.NewTokenStoreClient(m.cli.Conn())
	return client.RemoveToken(ctx, in, opts...)
}
