// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.1
// source: token_enhancer.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientDetails struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId                    string   `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	AccessTokenValiditySeconds  int64    `protobuf:"varint,2,opt,name=access_token_validity_seconds,json=accessTokenValiditySeconds,proto3" json:"access_token_validity_seconds,omitempty"`
	RefreshTokenValiditySeconds int64    `protobuf:"varint,3,opt,name=refresh_token_validity_seconds,json=refreshTokenValiditySeconds,proto3" json:"refresh_token_validity_seconds,omitempty"`
	RegisteredRedirectUri       string   `protobuf:"bytes,4,opt,name=registered_redirect_uri,json=registeredRedirectUri,proto3" json:"registered_redirect_uri,omitempty"`
	AuthorizedGrantTypes        []string `protobuf:"bytes,5,rep,name=authorized_grant_types,json=authorizedGrantTypes,proto3" json:"authorized_grant_types,omitempty"`
}

func (x *ClientDetails) Reset() {
	*x = ClientDetails{}
	if protoimpl.UnsafeEnabled {
		mi := &file_token_enhancer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientDetails) ProtoMessage() {}

func (x *ClientDetails) ProtoReflect() protoreflect.Message {
	mi := &file_token_enhancer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientDetails.ProtoReflect.Descriptor instead.
func (*ClientDetails) Descriptor() ([]byte, []int) {
	return file_token_enhancer_proto_rawDescGZIP(), []int{0}
}

func (x *ClientDetails) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ClientDetails) GetAccessTokenValiditySeconds() int64 {
	if x != nil {
		return x.AccessTokenValiditySeconds
	}
	return 0
}

func (x *ClientDetails) GetRefreshTokenValiditySeconds() int64 {
	if x != nil {
		return x.RefreshTokenValiditySeconds
	}
	return 0
}

func (x *ClientDetails) GetRegisteredRedirectUri() string {
	if x != nil {
		return x.RegisteredRedirectUri
	}
	return ""
}

func (x *ClientDetails) GetAuthorizedGrantTypes() []string {
	if x != nil {
		return x.AuthorizedGrantTypes
	}
	return nil
}

type UserDetails struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId      string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName    string   `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Nickname    string   `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	LastIp      string   `protobuf:"bytes,4,opt,name=last_ip,json=lastIp,proto3" json:"last_ip,omitempty"`
	Vip         int32    `protobuf:"varint,5,opt,name=vip,proto3" json:"vip,omitempty"`
	Status      string   `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	UpdateTime  string   `protobuf:"bytes,7,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	CreateTime  string   `protobuf:"bytes,8,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	Authorities []string `protobuf:"bytes,9,rep,name=authorities,proto3" json:"authorities,omitempty"`
}

func (x *UserDetails) Reset() {
	*x = UserDetails{}
	if protoimpl.UnsafeEnabled {
		mi := &file_token_enhancer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDetails) ProtoMessage() {}

func (x *UserDetails) ProtoReflect() protoreflect.Message {
	mi := &file_token_enhancer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDetails.ProtoReflect.Descriptor instead.
func (*UserDetails) Descriptor() ([]byte, []int) {
	return file_token_enhancer_proto_rawDescGZIP(), []int{1}
}

func (x *UserDetails) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserDetails) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *UserDetails) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserDetails) GetLastIp() string {
	if x != nil {
		return x.LastIp
	}
	return ""
}

func (x *UserDetails) GetVip() int32 {
	if x != nil {
		return x.Vip
	}
	return 0
}

func (x *UserDetails) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UserDetails) GetUpdateTime() string {
	if x != nil {
		return x.UpdateTime
	}
	return ""
}

func (x *UserDetails) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *UserDetails) GetAuthorities() []string {
	if x != nil {
		return x.Authorities
	}
	return nil
}

type OAuth2Details struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Client *ClientDetails `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
	User   *UserDetails   `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Issuer string         `protobuf:"bytes,3,opt,name=issuer,proto3" json:"issuer,omitempty"`
}

func (x *OAuth2Details) Reset() {
	*x = OAuth2Details{}
	if protoimpl.UnsafeEnabled {
		mi := &file_token_enhancer_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OAuth2Details) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OAuth2Details) ProtoMessage() {}

func (x *OAuth2Details) ProtoReflect() protoreflect.Message {
	mi := &file_token_enhancer_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OAuth2Details.ProtoReflect.Descriptor instead.
func (*OAuth2Details) Descriptor() ([]byte, []int) {
	return file_token_enhancer_proto_rawDescGZIP(), []int{2}
}

func (x *OAuth2Details) GetClient() *ClientDetails {
	if x != nil {
		return x.Client
	}
	return nil
}

func (x *OAuth2Details) GetUser() *UserDetails {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *OAuth2Details) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

type OAuth2Token struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RefreshToken *OAuth2Token `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	TokenType    string       `protobuf:"bytes,2,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	TokenValue   string       `protobuf:"bytes,3,opt,name=token_value,json=tokenValue,proto3" json:"token_value,omitempty"`
	ExpiresAt    int64        `protobuf:"varint,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
}

func (x *OAuth2Token) Reset() {
	*x = OAuth2Token{}
	if protoimpl.UnsafeEnabled {
		mi := &file_token_enhancer_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OAuth2Token) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OAuth2Token) ProtoMessage() {}

func (x *OAuth2Token) ProtoReflect() protoreflect.Message {
	mi := &file_token_enhancer_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OAuth2Token.ProtoReflect.Descriptor instead.
func (*OAuth2Token) Descriptor() ([]byte, []int) {
	return file_token_enhancer_proto_rawDescGZIP(), []int{3}
}

func (x *OAuth2Token) GetRefreshToken() *OAuth2Token {
	if x != nil {
		return x.RefreshToken
	}
	return nil
}

func (x *OAuth2Token) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *OAuth2Token) GetTokenValue() string {
	if x != nil {
		return x.TokenValue
	}
	return ""
}

func (x *OAuth2Token) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

// 根据用户认证生成访问令牌
type CreateAccessTokenReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Oauth2Details *OAuth2Details `protobuf:"bytes,1,opt,name=oauth2_details,json=oauth2Details,proto3" json:"oauth2_details,omitempty"`
}

func (x *CreateAccessTokenReq) Reset() {
	*x = CreateAccessTokenReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_token_enhancer_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAccessTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccessTokenReq) ProtoMessage() {}

func (x *CreateAccessTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_token_enhancer_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccessTokenReq.ProtoReflect.Descriptor instead.
func (*CreateAccessTokenReq) Descriptor() ([]byte, []int) {
	return file_token_enhancer_proto_rawDescGZIP(), []int{4}
}

func (x *CreateAccessTokenReq) GetOauth2Details() *OAuth2Details {
	if x != nil {
		return x.Oauth2Details
	}
	return nil
}

type CreateAccessTokenRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok   bool                       `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Msg  string                     `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data *CreateAccessTokenRes_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *CreateAccessTokenRes) Reset() {
	*x = CreateAccessTokenRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_token_enhancer_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAccessTokenRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccessTokenRes) ProtoMessage() {}

func (x *CreateAccessTokenRes) ProtoReflect() protoreflect.Message {
	mi := &file_token_enhancer_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccessTokenRes.ProtoReflect.Descriptor instead.
func (*CreateAccessTokenRes) Descriptor() ([]byte, []int) {
	return file_token_enhancer_proto_rawDescGZIP(), []int{5}
}

func (x *CreateAccessTokenRes) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *CreateAccessTokenRes) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *CreateAccessTokenRes) GetData() *CreateAccessTokenRes_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

// 根据刷新令牌生成访问令牌
type RefreshAccessTokenReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RefreshToken string `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
}

func (x *RefreshAccessTokenReq) Reset() {
	*x = RefreshAccessTokenReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_token_enhancer_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefreshAccessTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshAccessTokenReq) ProtoMessage() {}

func (x *RefreshAccessTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_token_enhancer_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshAccessTokenReq.ProtoReflect.Descriptor instead.
func (*RefreshAccessTokenReq) Descriptor() ([]byte, []int) {
	return file_token_enhancer_proto_rawDescGZIP(), []int{6}
}

func (x *RefreshAccessTokenReq) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RefreshAccessTokenRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok   bool                        `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Msg  string                      `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data *RefreshAccessTokenRes_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *RefreshAccessTokenRes) Reset() {
	*x = RefreshAccessTokenRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_token_enhancer_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefreshAccessTokenRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshAccessTokenRes) ProtoMessage() {}

func (x *RefreshAccessTokenRes) ProtoReflect() protoreflect.Message {
	mi := &file_token_enhancer_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshAccessTokenRes.ProtoReflect.Descriptor instead.
func (*RefreshAccessTokenRes) Descriptor() ([]byte, []int) {
	return file_token_enhancer_proto_rawDescGZIP(), []int{7}
}

func (x *RefreshAccessTokenRes) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *RefreshAccessTokenRes) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *RefreshAccessTokenRes) GetData() *RefreshAccessTokenRes_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

// 访问令牌结构体
type ReadTokenReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OauthToken string `protobuf:"bytes,1,opt,name=oauth_token,json=oauthToken,proto3" json:"oauth_token,omitempty"`
}

func (x *ReadTokenReq) Reset() {
	*x = ReadTokenReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_token_enhancer_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadTokenReq) ProtoMessage() {}

func (x *ReadTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_token_enhancer_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadTokenReq.ProtoReflect.Descriptor instead.
func (*ReadTokenReq) Descriptor() ([]byte, []int) {
	return file_token_enhancer_proto_rawDescGZIP(), []int{8}
}

func (x *ReadTokenReq) GetOauthToken() string {
	if x != nil {
		return x.OauthToken
	}
	return ""
}

type ReadTokenRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok   bool               `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Msg  string             `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data *ReadTokenRes_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ReadTokenRes) Reset() {
	*x = ReadTokenRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_token_enhancer_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadTokenRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadTokenRes) ProtoMessage() {}

func (x *ReadTokenRes) ProtoReflect() protoreflect.Message {
	mi := &file_token_enhancer_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadTokenRes.ProtoReflect.Descriptor instead.
func (*ReadTokenRes) Descriptor() ([]byte, []int) {
	return file_token_enhancer_proto_rawDescGZIP(), []int{9}
}

func (x *ReadTokenRes) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ReadTokenRes) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ReadTokenRes) GetData() *ReadTokenRes_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

// 获取令牌对应的用户信息
type GetUserDetailsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccessToken string `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
}

func (x *GetUserDetailsReq) Reset() {
	*x = GetUserDetailsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_token_enhancer_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserDetailsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserDetailsReq) ProtoMessage() {}

func (x *GetUserDetailsReq) ProtoReflect() protoreflect.Message {
	mi := &file_token_enhancer_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserDetailsReq.ProtoReflect.Descriptor instead.
func (*GetUserDetailsReq) Descriptor() ([]byte, []int) {
	return file_token_enhancer_proto_rawDescGZIP(), []int{10}
}

func (x *GetUserDetailsReq) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type GetUserDetailsRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok   bool                    `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Msg  string                  `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data *GetUserDetailsRes_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetUserDetailsRes) Reset() {
	*x = GetUserDetailsRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_token_enhancer_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserDetailsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserDetailsRes) ProtoMessage() {}

func (x *GetUserDetailsRes) ProtoReflect() protoreflect.Message {
	mi := &file_token_enhancer_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserDetailsRes.ProtoReflect.Descriptor instead.
func (*GetUserDetailsRes) Descriptor() ([]byte, []int) {
	return file_token_enhancer_proto_rawDescGZIP(), []int{11}
}

func (x *GetUserDetailsRes) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *GetUserDetailsRes) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetUserDetailsRes) GetData() *GetUserDetailsRes_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type CreateAccessTokenRes_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccessToken *OAuth2Token `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
}

func (x *CreateAccessTokenRes_Data) Reset() {
	*x = CreateAccessTokenRes_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_token_enhancer_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAccessTokenRes_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccessTokenRes_Data) ProtoMessage() {}

func (x *CreateAccessTokenRes_Data) ProtoReflect() protoreflect.Message {
	mi := &file_token_enhancer_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccessTokenRes_Data.ProtoReflect.Descriptor instead.
func (*CreateAccessTokenRes_Data) Descriptor() ([]byte, []int) {
	return file_token_enhancer_proto_rawDescGZIP(), []int{5, 0}
}

func (x *CreateAccessTokenRes_Data) GetAccessToken() *OAuth2Token {
	if x != nil {
		return x.AccessToken
	}
	return nil
}

type RefreshAccessTokenRes_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccessToken *OAuth2Token `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
}

func (x *RefreshAccessTokenRes_Data) Reset() {
	*x = RefreshAccessTokenRes_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_token_enhancer_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefreshAccessTokenRes_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshAccessTokenRes_Data) ProtoMessage() {}

func (x *RefreshAccessTokenRes_Data) ProtoReflect() protoreflect.Message {
	mi := &file_token_enhancer_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshAccessTokenRes_Data.ProtoReflect.Descriptor instead.
func (*RefreshAccessTokenRes_Data) Descriptor() ([]byte, []int) {
	return file_token_enhancer_proto_rawDescGZIP(), []int{7, 0}
}

func (x *RefreshAccessTokenRes_Data) GetAccessToken() *OAuth2Token {
	if x != nil {
		return x.AccessToken
	}
	return nil
}

type ReadTokenRes_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccessToken *OAuth2Token `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
}

func (x *ReadTokenRes_Data) Reset() {
	*x = ReadTokenRes_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_token_enhancer_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadTokenRes_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadTokenRes_Data) ProtoMessage() {}

func (x *ReadTokenRes_Data) ProtoReflect() protoreflect.Message {
	mi := &file_token_enhancer_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadTokenRes_Data.ProtoReflect.Descriptor instead.
func (*ReadTokenRes_Data) Descriptor() ([]byte, []int) {
	return file_token_enhancer_proto_rawDescGZIP(), []int{9, 0}
}

func (x *ReadTokenRes_Data) GetAccessToken() *OAuth2Token {
	if x != nil {
		return x.AccessToken
	}
	return nil
}

type GetUserDetailsRes_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserDetails *UserDetails `protobuf:"bytes,1,opt,name=user_details,json=userDetails,proto3" json:"user_details,omitempty"`
}

func (x *GetUserDetailsRes_Data) Reset() {
	*x = GetUserDetailsRes_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_token_enhancer_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserDetailsRes_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserDetailsRes_Data) ProtoMessage() {}

func (x *GetUserDetailsRes_Data) ProtoReflect() protoreflect.Message {
	mi := &file_token_enhancer_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserDetailsRes_Data.ProtoReflect.Descriptor instead.
func (*GetUserDetailsRes_Data) Descriptor() ([]byte, []int) {
	return file_token_enhancer_proto_rawDescGZIP(), []int{11, 0}
}

func (x *GetUserDetailsRes_Data) GetUserDetails() *UserDetails {
	if x != nil {
		return x.UserDetails
	}
	return nil
}

var File_token_enhancer_proto protoreflect.FileDescriptor

var file_token_enhancer_proto_rawDesc = []byte{
	0x0a, 0x14, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x65, 0x6e, 0x68, 0x61, 0x6e, 0x63, 0x65, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x65, 0x6e, 0x68, 0x61, 0x6e, 0x63, 0x65, 0x72,
	0x22, 0xa2, 0x02, 0x0a, 0x0d, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12,
	0x41, 0x0a, 0x1d, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f,
	0x76, 0x61, 0x6c, 0x69, 0x64, 0x69, 0x74, 0x79, 0x5f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x1a, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x69, 0x74, 0x79, 0x53, 0x65, 0x63, 0x6f, 0x6e,
	0x64, 0x73, 0x12, 0x43, 0x0a, 0x1e, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x5f, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x5f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x69, 0x74, 0x79, 0x5f, 0x73, 0x65, 0x63,
	0x6f, 0x6e, 0x64, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x1b, 0x72, 0x65, 0x66, 0x72,
	0x65, 0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x69, 0x74, 0x79,
	0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x12, 0x36, 0x0a, 0x17, 0x72, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x65, 0x64, 0x5f, 0x72, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x5f, 0x75,
	0x72, 0x69, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x15, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x65, 0x72, 0x65, 0x64, 0x52, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x55, 0x72, 0x69, 0x12,
	0x34, 0x0a, 0x16, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x64, 0x5f, 0x67, 0x72,
	0x61, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x14, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x64, 0x47, 0x72, 0x61, 0x6e, 0x74,
	0x54, 0x79, 0x70, 0x65, 0x73, 0x22, 0x86, 0x02, 0x0a, 0x0b, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1b,
	0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6e,
	0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e,
	0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x6c, 0x61, 0x73, 0x74, 0x5f,
	0x69, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6c, 0x61, 0x73, 0x74, 0x49, 0x70,
	0x12, 0x10, 0x0a, 0x03, 0x76, 0x69, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x76,
	0x69, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b,
	0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x74, 0x69, 0x65, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x0b, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x74, 0x69, 0x65, 0x73, 0x22, 0x83,
	0x01, 0x0a, 0x0d, 0x4f, 0x41, 0x75, 0x74, 0x68, 0x32, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73,
	0x12, 0x2f, 0x0a, 0x06, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x17, 0x2e, 0x65, 0x6e, 0x68, 0x61, 0x6e, 0x63, 0x65, 0x72, 0x2e, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x06, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x12, 0x29, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x15, 0x2e, 0x65, 0x6e, 0x68, 0x61, 0x6e, 0x63, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06,
	0x69, 0x73, 0x73, 0x75, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x69, 0x73,
	0x73, 0x75, 0x65, 0x72, 0x22, 0xa8, 0x01, 0x0a, 0x0b, 0x4f, 0x41, 0x75, 0x74, 0x68, 0x32, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x3a, 0x0a, 0x0d, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x5f,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x65, 0x6e,
	0x68, 0x61, 0x6e, 0x63, 0x65, 0x72, 0x2e, 0x4f, 0x41, 0x75, 0x74, 0x68, 0x32, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x52, 0x0c, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x1f, 0x0a, 0x0b, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x73, 0x5f, 0x61, 0x74, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x73, 0x41, 0x74, 0x22,
	0x56, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x3e, 0x0a, 0x0e, 0x6f, 0x61, 0x75, 0x74, 0x68,
	0x32, 0x5f, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x17, 0x2e, 0x65, 0x6e, 0x68, 0x61, 0x6e, 0x63, 0x65, 0x72, 0x2e, 0x4f, 0x41, 0x75, 0x74, 0x68,
	0x32, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x0d, 0x6f, 0x61, 0x75, 0x74, 0x68, 0x32,
	0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x22, 0xb3, 0x01, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73,
	0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b,
	0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d,
	0x73, 0x67, 0x12, 0x37, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x23, 0x2e, 0x65, 0x6e, 0x68, 0x61, 0x6e, 0x63, 0x65, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73,
	0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x40, 0x0a, 0x04, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x38, 0x0a, 0x0c, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x65, 0x6e, 0x68, 0x61,
	0x6e, 0x63, 0x65, 0x72, 0x2e, 0x4f, 0x41, 0x75, 0x74, 0x68, 0x32, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x52, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x3c, 0x0a,
	0x15, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73,
	0x68, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72,
	0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0xb5, 0x01, 0x0a, 0x15,
	0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x52, 0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x38, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x65, 0x6e, 0x68, 0x61, 0x6e, 0x63, 0x65, 0x72,
	0x2e, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x1a, 0x40, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x38, 0x0a, 0x0c, 0x61, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x15, 0x2e, 0x65, 0x6e, 0x68, 0x61, 0x6e, 0x63, 0x65, 0x72, 0x2e, 0x4f, 0x41, 0x75, 0x74, 0x68,
	0x32, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x22, 0x2f, 0x0a, 0x0c, 0x52, 0x65, 0x61, 0x64, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x52, 0x65, 0x71, 0x12, 0x1f, 0x0a, 0x0b, 0x6f, 0x61, 0x75, 0x74, 0x68, 0x5f, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6f, 0x61, 0x75, 0x74, 0x68, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x22, 0xa3, 0x01, 0x0a, 0x0c, 0x52, 0x65, 0x61, 0x64, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x52, 0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x2f, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x65, 0x6e, 0x68, 0x61, 0x6e, 0x63, 0x65, 0x72,
	0x2e, 0x52, 0x65, 0x61, 0x64, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x2e, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x40, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x38, 0x0a, 0x0c, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x65, 0x6e, 0x68, 0x61, 0x6e, 0x63, 0x65,
	0x72, 0x2e, 0x4f, 0x41, 0x75, 0x74, 0x68, 0x32, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x0b, 0x61,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x36, 0x0a, 0x11, 0x47, 0x65,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x12,
	0x21, 0x0a, 0x0c, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x22, 0xad, 0x01, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x34, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x65, 0x6e, 0x68, 0x61, 0x6e,
	0x63, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x73, 0x52, 0x65, 0x73, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x1a, 0x40, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x38, 0x0a, 0x0c, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15,
	0x2e, 0x65, 0x6e, 0x68, 0x61, 0x6e, 0x63, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x73, 0x32, 0xca, 0x02, 0x0a, 0x0d, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x45, 0x6e, 0x68, 0x61,
	0x6e, 0x63, 0x65, 0x72, 0x12, 0x53, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1e, 0x2e, 0x65, 0x6e, 0x68, 0x61,
	0x6e, 0x63, 0x65, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x1e, 0x2e, 0x65, 0x6e, 0x68, 0x61,
	0x6e, 0x63, 0x65, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x12, 0x56, 0x0a, 0x12, 0x52, 0x65, 0x66,
	0x72, 0x65, 0x73, 0x68, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12,
	0x1f, 0x2e, 0x65, 0x6e, 0x68, 0x61, 0x6e, 0x63, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x66, 0x72, 0x65,
	0x73, 0x68, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71,
	0x1a, 0x1f, 0x2e, 0x65, 0x6e, 0x68, 0x61, 0x6e, 0x63, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x66, 0x72,
	0x65, 0x73, 0x68, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65,
	0x73, 0x12, 0x40, 0x0a, 0x0e, 0x52, 0x65, 0x61, 0x64, 0x4f, 0x61, 0x75, 0x74, 0x68, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x12, 0x16, 0x2e, 0x65, 0x6e, 0x68, 0x61, 0x6e, 0x63, 0x65, 0x72, 0x2e, 0x52,
	0x65, 0x61, 0x64, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x65, 0x6e,
	0x68, 0x61, 0x6e, 0x63, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x52, 0x65, 0x73, 0x12, 0x4a, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x1b, 0x2e, 0x65, 0x6e, 0x68, 0x61, 0x6e, 0x63, 0x65, 0x72,
	0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52,
	0x65, 0x71, 0x1a, 0x1b, 0x2e, 0x65, 0x6e, 0x68, 0x61, 0x6e, 0x63, 0x65, 0x72, 0x2e, 0x47, 0x65,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x42,
	0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_token_enhancer_proto_rawDescOnce sync.Once
	file_token_enhancer_proto_rawDescData = file_token_enhancer_proto_rawDesc
)

func file_token_enhancer_proto_rawDescGZIP() []byte {
	file_token_enhancer_proto_rawDescOnce.Do(func() {
		file_token_enhancer_proto_rawDescData = protoimpl.X.CompressGZIP(file_token_enhancer_proto_rawDescData)
	})
	return file_token_enhancer_proto_rawDescData
}

var file_token_enhancer_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_token_enhancer_proto_goTypes = []interface{}{
	(*ClientDetails)(nil),              // 0: enhancer.ClientDetails
	(*UserDetails)(nil),                // 1: enhancer.UserDetails
	(*OAuth2Details)(nil),              // 2: enhancer.OAuth2Details
	(*OAuth2Token)(nil),                // 3: enhancer.OAuth2Token
	(*CreateAccessTokenReq)(nil),       // 4: enhancer.CreateAccessTokenReq
	(*CreateAccessTokenRes)(nil),       // 5: enhancer.CreateAccessTokenRes
	(*RefreshAccessTokenReq)(nil),      // 6: enhancer.RefreshAccessTokenReq
	(*RefreshAccessTokenRes)(nil),      // 7: enhancer.RefreshAccessTokenRes
	(*ReadTokenReq)(nil),               // 8: enhancer.ReadTokenReq
	(*ReadTokenRes)(nil),               // 9: enhancer.ReadTokenRes
	(*GetUserDetailsReq)(nil),          // 10: enhancer.GetUserDetailsReq
	(*GetUserDetailsRes)(nil),          // 11: enhancer.GetUserDetailsRes
	(*CreateAccessTokenRes_Data)(nil),  // 12: enhancer.CreateAccessTokenRes.Data
	(*RefreshAccessTokenRes_Data)(nil), // 13: enhancer.RefreshAccessTokenRes.Data
	(*ReadTokenRes_Data)(nil),          // 14: enhancer.ReadTokenRes.Data
	(*GetUserDetailsRes_Data)(nil),     // 15: enhancer.GetUserDetailsRes.Data
}
var file_token_enhancer_proto_depIdxs = []int32{
	0,  // 0: enhancer.OAuth2Details.client:type_name -> enhancer.ClientDetails
	1,  // 1: enhancer.OAuth2Details.user:type_name -> enhancer.UserDetails
	3,  // 2: enhancer.OAuth2Token.refresh_token:type_name -> enhancer.OAuth2Token
	2,  // 3: enhancer.CreateAccessTokenReq.oauth2_details:type_name -> enhancer.OAuth2Details
	12, // 4: enhancer.CreateAccessTokenRes.data:type_name -> enhancer.CreateAccessTokenRes.Data
	13, // 5: enhancer.RefreshAccessTokenRes.data:type_name -> enhancer.RefreshAccessTokenRes.Data
	14, // 6: enhancer.ReadTokenRes.data:type_name -> enhancer.ReadTokenRes.Data
	15, // 7: enhancer.GetUserDetailsRes.data:type_name -> enhancer.GetUserDetailsRes.Data
	3,  // 8: enhancer.CreateAccessTokenRes.Data.access_token:type_name -> enhancer.OAuth2Token
	3,  // 9: enhancer.RefreshAccessTokenRes.Data.access_token:type_name -> enhancer.OAuth2Token
	3,  // 10: enhancer.ReadTokenRes.Data.access_token:type_name -> enhancer.OAuth2Token
	1,  // 11: enhancer.GetUserDetailsRes.Data.user_details:type_name -> enhancer.UserDetails
	4,  // 12: enhancer.TokenEnhancer.CreateAccessToken:input_type -> enhancer.CreateAccessTokenReq
	6,  // 13: enhancer.TokenEnhancer.RefreshAccessToken:input_type -> enhancer.RefreshAccessTokenReq
	8,  // 14: enhancer.TokenEnhancer.ReadOauthToken:input_type -> enhancer.ReadTokenReq
	10, // 15: enhancer.TokenEnhancer.GetUserDetails:input_type -> enhancer.GetUserDetailsReq
	5,  // 16: enhancer.TokenEnhancer.CreateAccessToken:output_type -> enhancer.CreateAccessTokenRes
	7,  // 17: enhancer.TokenEnhancer.RefreshAccessToken:output_type -> enhancer.RefreshAccessTokenRes
	9,  // 18: enhancer.TokenEnhancer.ReadOauthToken:output_type -> enhancer.ReadTokenRes
	11, // 19: enhancer.TokenEnhancer.GetUserDetails:output_type -> enhancer.GetUserDetailsRes
	16, // [16:20] is the sub-list for method output_type
	12, // [12:16] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_token_enhancer_proto_init() }
func file_token_enhancer_proto_init() {
	if File_token_enhancer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_token_enhancer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientDetails); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_token_enhancer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserDetails); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_token_enhancer_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OAuth2Details); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_token_enhancer_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OAuth2Token); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_token_enhancer_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAccessTokenReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_token_enhancer_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAccessTokenRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_token_enhancer_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefreshAccessTokenReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_token_enhancer_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefreshAccessTokenRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_token_enhancer_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadTokenReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_token_enhancer_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadTokenRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_token_enhancer_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserDetailsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_token_enhancer_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserDetailsRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_token_enhancer_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAccessTokenRes_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_token_enhancer_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefreshAccessTokenRes_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_token_enhancer_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadTokenRes_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_token_enhancer_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserDetailsRes_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_token_enhancer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_token_enhancer_proto_goTypes,
		DependencyIndexes: file_token_enhancer_proto_depIdxs,
		MessageInfos:      file_token_enhancer_proto_msgTypes,
	}.Build()
	File_token_enhancer_proto = out.File
	file_token_enhancer_proto_rawDesc = nil
	file_token_enhancer_proto_goTypes = nil
	file_token_enhancer_proto_depIdxs = nil
}
