// Code generated by goctl. DO NOT EDIT.
package types

type GetNotificationReq struct {
	NotificationId int64 `path:"notification_id"`
}

type GetNotificationRes struct {
	Code int32  `json:"code"`
	Msg  string `json:"msg"`
	Ok   bool   `json:"ok"`
	Data string `json:"data"`
}
