// Code generated by goctl. DO NOT EDIT!
// Source: info.proto

package server

import (
	"context"

	"main/app/service/comment/rpc/info/internal/logic"
	"main/app/service/comment/rpc/info/internal/svc"
	"main/app/service/comment/rpc/info/pb"
)

type InfoServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedInfoServer
}

func NewInfoServer(svcCtx *svc.ServiceContext) *InfoServer {
	return &InfoServer{
		svcCtx: svcCtx,
	}
}

func (s *InfoServer) GetCommentSubject(ctx context.Context, in *pb.GetCommentSubjectReq) (*pb.GetCommentSubjectRes, error) {
	l := logic.NewGetCommentSubjectLogic(ctx, s.svcCtx)
	return l.GetCommentSubject(in)
}

func (s *InfoServer) GetCommentInfo(ctx context.Context, in *pb.GetCommentInfoReq) (*pb.GetCommentInfoRes, error) {
	l := logic.NewGetCommentInfoLogic(ctx, s.svcCtx)
	return l.GetCommentInfo(in)
}

func (s *InfoServer) GetCommentSubjectIndex(ctx context.Context, in *pb.GetCommentSubjectIndexReq) (*pb.GetCommentSubjectIndexRes, error) {
	l := logic.NewGetCommentSubjectIndexLogic(ctx, s.svcCtx)
	return l.GetCommentSubjectIndex(in)
}
