// Code generated by goctl. DO NOT EDIT!
// Source: info.proto

package server

import (
	"context"

	"main/app/service/notification/rpc/info/internal/logic"
	"main/app/service/notification/rpc/info/internal/svc"
	"main/app/service/notification/rpc/info/pb"
)

type InfoServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedInfoServer
}

func NewInfoServer(svcCtx *svc.ServiceContext) *InfoServer {
	return &InfoServer{
		svcCtx: svcCtx,
	}
}

func (s *InfoServer) GetNotification(ctx context.Context, in *pb.GetNotificationReq) (*pb.GetNotificationRes, error) {
	l := logic.NewGetNotificationLogic(ctx, s.svcCtx)
	return l.GetNotification(in)
}
