// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	UID        int64     `gorm:"column:uid;primaryKey" json:"uid"`
	Nickname   string    `gorm:"column:nickname;not null" json:"nickname"`
	Password   string    `gorm:"column:password;not null" json:"password"`
	Email      string    `gorm:"column:email" json:"email"`
	Phone      string    `gorm:"column:phone" json:"phone"`
	LastIP     string    `gorm:"column:last_ip" json:"last_ip"`
	Vip        int32     `gorm:"column:vip;not null" json:"vip"`
	Status     int32     `gorm:"column:status" json:"status"`
	UpdateTime time.Time `gorm:"column:update_time;not null" json:"update_time"`
	CreateTime time.Time `gorm:"column:create_time;not null" json:"create_time"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
