// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserSubscribe = "user_subscribe"

// UserSubscribe mapped from table <user_subscribe>
type UserSubscribe struct {
	UserID     int64     `gorm:"column:user_id;primaryKey" json:"user_id"`                      // 用户 ID
	ObjID      int64     `gorm:"column:obj_id;not null" json:"obj_id"`                          // 对象 id
	ObjType    int32     `gorm:"column:obj_type;not null" json:"obj_type"`                      // 对象类型 (0-默认对象 1-问题 2-回答 3-文章 4-话题)
	CreateTime time.Time `gorm:"autoCreateTime;column:create_time;not null" json:"create_time"` // 创建时间
	UpdateTime time.Time `gorm:"autoUpdateTime;column:update_time;not null" json:"update_time"` // 修改时间
}

// TableName UserSubscribe's table name
func (*UserSubscribe) TableName() string {
	return TableNameUserSubscribe
}
