// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"main/app/service/question/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/api/question/crud",
					Handler: CrudHandler(serverCtx),
				},
			}...,
		),
	)
}
