// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCommentContent = "comment_content"

// CommentContent mapped from table <comment_content>
type CommentContent struct {
	CommentID  int64     `gorm:"column:comment_id;primaryKey" json:"comment_id"`                // 主键 (评论/回复 id)
	Content    string    `gorm:"column:content" json:"content"`                                 // 评论/回复 内容
	Meta       string    `gorm:"column:meta" json:"meta"`                                       // 元数据
	CreateTime time.Time `gorm:"autoCreateTime;column:create_time;not null" json:"create_time"` // 创建时间
	UpdateTime time.Time `gorm:"autoUpdateTime;column:update_time;not null" json:"update_time"` // 修改时间
}

// TableName CommentContent's table name
func (*CommentContent) TableName() string {
	return TableNameCommentContent
}
